<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/facebookplugin/facebook.css') ?>"/>
<div class="fb-page"
     data-href="<?php echo $this->getUrl(); ?>"
     <?php if ($this->getTabs()): ?>
         data-tabs="<?php echo $this->getTabs(); ?>"
     <?php endif; ?>
     <?php if ($this->getHeight()): ?>
         data-height="<?php echo $this->getHeight(); ?>"
     <?php endif; ?>
     <?php if ($this->getWidth()): ?>
         data-width="<?php echo $this->getWidth(); ?>"
     <?php endif; ?>
     <?php if ($this->getSmallHeader()): ?>
         data-small-header="<?php echo $this->getSmallHeader(); ?>"
     <?php endif; ?>
     <?php if ($this->getHideCover()): ?>
         data-hide-cover="<?php echo $this->getHideCover(); ?>"
     <?php endif; ?>
     <?php if ($this->getShowFacepile()): ?>
         data-show-facepile="<?php echo $this->getShowFacepile(); ?>"
     <?php endif; ?>
     >
    <blockquote cite="<?php echo $this->getUrl(); ?>" class="fb-xfbml-parse-ignore">
        <a href="<?php echo $this->getUrl(); ?>"><?php echo $this->getPluginName(); ?></a>
    </blockquote>
</div>

